'use strict';
/**
 * Gemeinsame GitHub-Helfer fuer die CI-Skripte: Markerbloecke in eine
 * Beschreibung einpflegen, PR- und Issue-Bodies patchen, Kommentare posten.
 * Ohne Dependencies, Node >= 18 (globales fetch).
 *
 * Extrahiert aus scripts/pr-summary.js, damit costs-merge.mjs dieselbe
 * Marker-Logik nutzt statt sie ein zweites Mal zu schreiben.
 */

const API_ROOT = 'https://api.github.com';

// Jeder Kommentar, den ein CI-Job schreibt, weist sich als generiert aus.
const ATTRIBUTION = '---\n_Generated by [Claude Code](https://claude.ai/code)_';
const ATTRIBUTION_NEEDLE = '_Generated by [Claude Code]';

/**
 * Marker als Paar aufloesen: entweder ein Name ("cost-summary") oder ein
 * fertiges { start, end }.
 * @param {string|{start: string, end: string}} marker
 */
function markerPair(marker) {
  if (marker && typeof marker === 'object') return marker;
  return { start: `<!-- ${marker}:start -->`, end: `<!-- ${marker}:end -->` };
}

/**
 * Block zwischen den Markern ersetzen, sonst hinten anhaengen. Damit doppelt
 * ein zweiter Lauf nichts, egal wie oft er laeuft.
 *
 * @param {string|null} existingBody Bisherige Beschreibung
 * @param {string} block Inhalt zwischen den Markern (ohne Marker)
 * @param {string|{start: string, end: string}} marker
 * @returns {string} Neue Beschreibung
 */
function mergeIntoBody(existingBody, block, marker) {
  const { start, end } = markerPair(marker);
  const wrapped = `${start}\n${block}\n${end}`;
  const current = existingBody || '';

  const from = current.indexOf(start);
  const to = from === -1 ? -1 : current.indexOf(end, from + start.length);
  if (from !== -1 && to !== -1) {
    return current.slice(0, from) + wrapped + current.slice(to + end.length);
  }
  return current.trim() ? `${current.trim()}\n\n${wrapped}` : wrapped;
}

/**
 * Roher API-Aufruf. Wirft bei jedem Status ausserhalb 2xx.
 * @param {string} path Pfad ab /repos/...
 * @param {RequestInit} [init]
 */
async function api(path, init = {}) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('Missing env var: GITHUB_TOKEN');

  const res = await fetch(`${API_ROOT}${path}`, {
    ...init,
    headers: {
      accept: 'application/vnd.github+json',
      authorization: `Bearer ${token}`,
      'x-github-api-version': '2022-11-28',
      'content-type': 'application/json',
      ...(init.headers || {}),
    },
  });
  if (!res.ok) throw new Error(`GitHub API ${res.status} bei ${path}: ${await res.text()}`);
  if (res.status === 204) return null;
  return res.json();
}

/**
 * PR oder Issue lesen.
 * @param {string} repo "owner/name"
 * @param {number|string} number
 * @param {'pulls'|'issues'} [kind]
 */
async function get(repo, number, kind = 'pulls') {
  return api(`/repos/${repo}/${kind}/${number}`);
}

/**
 * Beschreibung eines PR oder Issues schreiben.
 * @param {string} repo "owner/name"
 * @param {number|string} number
 * @param {string} body
 * @param {'pulls'|'issues'} [kind]
 */
async function patchBody(repo, number, body, kind = 'pulls') {
  return api(`/repos/${repo}/${kind}/${number}`, {
    method: 'PATCH',
    body: JSON.stringify({ body }),
  });
}

/**
 * Kommentare eines PR oder Issues lesen (erste 100 Seiten a 100 Stueck).
 * @param {string} repo "owner/name"
 * @param {number|string} number
 */
async function listComments(repo, number) {
  const all = [];
  for (let page = 1; page <= 100; page++) {
    const batch = await api(`/repos/${repo}/issues/${number}/comments?per_page=100&page=${page}`);
    if (!Array.isArray(batch) || batch.length === 0) break;
    all.push(...batch);
    if (batch.length < 100) break;
  }
  return all;
}

/**
 * Kommentar posten. Die Attributions-Fussnote haengt der Helfer selbst an -
 * so kann sie kein Aufrufer vergessen.
 * @param {string} repo "owner/name"
 * @param {number|string} number
 * @param {string} body
 */
async function comment(repo, number, body) {
  const text = String(body).trimEnd();
  const withFooter = text.includes(ATTRIBUTION_NEEDLE) ? text : `${text}\n\n${ATTRIBUTION}`;
  return api(`/repos/${repo}/issues/${number}/comments`, {
    method: 'POST',
    body: JSON.stringify({ body: withFooter }),
  });
}

module.exports = {
  ATTRIBUTION,
  api,
  comment,
  get,
  listComments,
  markerPair,
  mergeIntoBody,
  patchBody,
};
